name: ETL - Programado

on:
  # Edita la expresión cron abajo para fijar la fecha/horario deseado (UTC)
  schedule:
    - cron: '0 7 1 * *' # ejemplo: cada mes el día 15 a las 06:00 UTC
  workflow_dispatch:
    inputs:
      cron:
        description: 'Cron schedule (opcional) — referencia'
        required: false

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run ETL pipeline
        run: |
          python etl/pipeline.py

      - name: Upload logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: etl-logs
          path: |
            ./logs/**
            ./etl/logs/**

# Notas:
# - Modifica la línea `cron` en la sección `schedule` para ajustar la fecha/horario.
# - GitHub Actions usa UTC para cron expressions.
# - Ejemplos de cron:
#   - Cada mes día 27 a 09:00 UTC: '0 9 27 * *'
#   - Cada año 27 diciembre a 09:00 UTC: '0 9 27 12 *'